replicaCount: 1
image:
  repository: ghcr.io/<github-username>/fiforesight
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets:
  - name: ghcr-secret

serviceAccount:
  create: true
  annotations: {}
  name: "sa"

podAnnotations: {}

service:
  type: LoadBalancer
  port: 80
  targetPort: 3000

resources:
  limits:
    memory: 1024Mi
  requests:
    cpu: 250m
    memory: 512Mi

nodeSelector: {}
tolerations: []
affinity: {}
