name: Docker logs
permissions:
  contents: read
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        options:
          - preview
          - live
        default: live
        required: true
        description: "Select the environment to get logs"

jobs:
  retrieve-logs:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: 1.14.8
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        working-directory: ${{ (inputs.environment == 'preview' && 'terraform-preview') || 'terraform' }}
        shell: bash
        run: terraform init

      - name: Get Terraform Outputs
        id: tf_outputs
        working-directory: ${{ (inputs.environment == 'preview' && 'terraform-preview') || 'terraform' }}
        run: |
          PUBLIC_IP=$(terraform output -raw public_ip)
          echo "public_ip=$PUBLIC_IP" >> $GITHUB_OUTPUT

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VM_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ steps.tf_outputs.outputs.public_ip }} >> ~/.ssh/known_hosts

      - name: SSH and save logs
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@${{ steps.tf_outputs.outputs.public_ip }} \
            "docker logs fiforesight 2>&1" | tee docker.log

      - name: Show log
        run: tail -100 docker.log

      - name: Write to step summary
        run: |
          echo '## fiforesight container logs from ${{ inputs.environment }} environment' >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          tail -100 docker.log >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

      - name: Upload log as artifact
        uses: actions/upload-artifact@v7
        with:
          name: docker-logs
          path: docker.log