name: Node build
on:
  pull_request:
    branches:
      - "**"
    paths:
      - "frontend/**"

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        working-directory: frontend
        shell: bash
        run: npm install --global pnpm

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 'latest'

      - name: Install Dependencies
        working-directory: frontend
        shell: bash
        run: pnpm install --lockfile

      - name: Run Build
        working-directory: frontend
        shell: bash
        run: pnpm run build