name: Node build
on:
  pull_request:
    branches:
      - "**"
    paths:
      - "frontend/**"

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          cache-dependency-path: frontend/pnpm-lock.yaml

      - name: Install Dependencies
        working-directory: frontend
        run: pnpm install --no-frozen-lockfile

      - name: Run Build
        working-directory: frontend
        run: pnpm run build
